### ISSUE TITLE
Coding standards e boas práticas

### ISSUE THREAD

**Issue by quetzyg** [vostpt/api#1]
Sugiro usar o [PHP CS Fixer](https://cs.symfony.com) com um conjunto de regras a discutir (PSR-2, etc), para que o código seja consistente, independentemente de quem está a trabalhar no projecto.

Algo que também deveria ser tomado em consideração é o uso de [Semantic Commit Messages](https://seesparkbox.com/foundry/semantic_commit_messages).

**Comment by quetzyg** [comment]
Outra coisa a ter em conta é a lingua usada. Embora sejamos na maioria portugueses, de forma a haver uma melhor interoperabilidade, devemos ter o código escrito (variáveis, etc) e comentado em inglês.

**Comment by PJFonseca** [comment]
Completamente de acordo em tudo. Inglês deve ser a lingua base e o PSR-2 é algo que nem deve ser discutido.

**Comment by quetzyg** [comment]
Já resolvido no `master`.
