### ISSUE TITLE
Windy API (https://api4.windy.com/)

### ISSUE THREAD

**Issue by L3v3L** [vostpt/api#11]

**Comment by L3v3L** [comment]
I think we will have issues implementing the Windy API as its a javascript plugin for [leafletjs](https://leafletjs.com/)
It seem like it's mostly used for adding a layer of windy data onto a map element on a page.

**Comment by quetzyg** [comment]
We can take a look and see where the real data is coming from, then.

**Comment by quetzyg** [comment]
Closing due to lack interest.
