### ISSUE TITLE
[FEAT] Important events 

### ISSUE THREAD

**Issue by JorgeMiguelGomes** [vostpt/api#35]
ANEPC's website joins a series of occurrences into something they call "Meteorologia Adversa" and that VOST Portugal calls **"#FMA"** followed by the name of the event and country code
**_`Example: #FMALesliePT`_** 

For "Meteorologia Adversa" these are the codes that are joined into one type:
`['3315', '3317', '3301', '4305', '3309', '2419', '3313', '3319', '3321', '3329', '4329', '4339']`

The official criteria for an "Important event" is:

​​

> As ocorrências d​​a classe "Incêndio Rural" contemplam incêndios e​​m povoamento, áreas de inculto/mato e áreas agrícolas. A classe "Meteorologia Adversa" inclui naturezas que, tradicionalmente, têm na sua origem meteorologia de inverno embora possam ocorrer em qualquer momento do ano (tal como os incêndios rurais) e incluem quedas de árvore, movimentos de massa, inundações, quedas de estruturas,​ limpezas de via, e salvamentos terrestres e aquáticos. Todas as outras operações de proteção e socorro que não se incluam nas aqui referidas, assumem a simbologia genérica de "Todas as Ocorrências". As ocorrências da classe "Incêndio Rural" consideradas como importantes são as de duração superior a 3 horas e com mais de 15 meios de proteção e socorro envolvidos.

Summary:

**Incêndio Rural**: any event from the category "Incêndio Rural" that has been active for more than 3h and with more than 15 support vehicles  (these include air support) 

**Meteorologia Adversa**: Anytime that an FMA is declared by IPMA, AEMET, or MeteoFrance and that will affect the Portuguese territory (mainland or islands)

**Comment by quetzyg** [comment]
Currently, we can already do this by choosing the `OccurrenceType` ids we want via https://api.vost.pt/documentation/#operation/occurrences::types::index and then, filter `Occurrence` records using the `type` argument, passing the ids we got from the previous endpoint.

**Comment by josepostiga** [comment]
Can't really understand what you're talking, here, but since @quetzyg said it's already possible to be done, I'll go ahead and close this.

Please, if there's something missing don't hesitate to reopen this, but give a well-defined intention of work to be done.
