### ISSUE TITLE
[FEAT] Number of type of occurrences given dates

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/api#38]
### Descrição

Seria interessante ter um endpoint que dado o _family/species/type/_ de uma ocorrência e duas datas, retorna quantas ocorreram, terminaram ou ainda estão a decorrer. Sem referir datas, retornaria o número a decorrer e respectiva informação no momento.

_Nice to have: A possibilidade de filtrar por District/County/Parish_

---
### História

**Maria** : 25-35 anos, jornalista de investigação, escreve artigos de opinião para jornais, procura estar ao corrente dos últimos acontecimentos

- "Como Maria, quero saber quantas 'Quedas de árvore' (occurence type) estão a ocorrer, para ter uma noção do número nacional."

- "Como Maria, quero saber desde do início do ano quantos 'Riscos Tecnológicos' (occurrence family), para determinar se este ano tem sido anormal versus o ano anterior."

/cc @JorgeMiguelGomes

**Comment by quetzyg** [comment]
Fixed via #42
