### ISSUE TITLE
[FEAT] Move "IPMA Warnings" from legacy API

### ISSUE THREAD

**Issue by gadelhas** [vostpt/api#41]
Our old API has a feature that gathers all the IPMA warnings and sends them via HTTP in a way our bot can understand.

The link is here: https://bot-api.vost.pt/getAvisosIPMA.php

Old code is: https://gist.github.com/gadelhas/eca475790f6a37ad2674c16a330e1991

**Comment by ClaudioVarandas** [comment]
Fetch schedule is hourly.

**Comment by ClaudioVarandas** [comment]
Did some work here https://github.com/vostpt/api/tree/feature/API-41-migrate-IPMA-Warnings, using the json encapsulated inside the index.html from the website.
But as discussed with @quetzyg and i agree too, there is no trusted identifiers to store the data in the DB and compare the data in the data with the data fetched to create/update.

This issue requires some brainstorming and detailed discussion.

**Comment by gadelhas** [comment]
For now, can we just fetch and don't store historical data? 

Just so the bot has an API to work with.

**Comment by ClaudioVarandas** [comment]
yes, sure , i will create a temporary table to work as a buffer.

**Comment by quetzyg** [comment]
If that's the case, shouldn't the bot just fetch the data directly?

**Comment by gadelhas** [comment]
Because the bot should only retrieve information from our API, that way we only have it going to one source and not different ones.
Going to multiple sources is the API job.

**Comment by quetzyg** [comment]
I get the point, but in this specific case it should just fetch the data straight from the source, mainly because there's no added value, it would just act as a proxy.

Prociv data gets normalised and stored, allowing you to search, filter, sort, etc. 

But as it stands, the IPMA data doesn't allow us to do that, since it lacks a proper identifier per record to begin with, making it hard to know what is new and what is updated when storing data.

And then, there's the JSON API spec, which would have to be respected, because the last thing I would like is the API to start spitting hacky response structures just to accommodate for a weird use case.

**Comment by gadelhas** [comment]
The thing here is, we can retrieve data from the API, delete all the old ones, and store new ones and with this we will have JSON:API specced answer that the bot, dashboard and app can get, without going to multiple sources.

And then, when we have a way of storing historical data with proper identifiers, we will revise this issue.

You need to keep in mind that all our elements will need to retrieve all the data they need from this API. It's our job to normalize data and send out with JSON:API responses, even if for now we just act as a proxy. 
I don't want any APP, Dashboard or bot to go retrieve data from outside sources.

**Comment by quetzyg** [comment]
Alright, let's give this a go, then. I already had the client done, so I'll push a branch with that.

**Comment by ClaudioVarandas** [comment]
Hi,
I'm also not a fan how this way of fetching data, but its a step forward to have everything in one place the VOST API, lets hope in a near future, we can change this when IPMA make the warnings available in theirs JSON API. Just my opinion. :)

**Comment by quetzyg** [comment]
Fixed via #43
