### ISSUE TITLE
[FEAT] Search Occurrences given a list of ids

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/api#49]
**Request**
To return the occurrences given a list of IDs, in the Occurrences / Index Occurrences
https://api.vost.pt/documentation/#tag/Occurrences

**Use Case:**
A person has a list of "following" (favorite) occurrences when opening the screen of favorites, it will load the respective occurrences that it was following.

**Comment by mribeiro** [comment]
Isn't this already done?
Looking at the documentation you're referring to I see this query parameter:

```
events
Array of strings
Filter by Event ids
```

**Comment by quetzyg** [comment]
Hi @mribeiro ,

While synonyms, we consider `Events` a group of `Occurrences`. Meaning that `Occurrences` about the same thing from different sources, can be grouped into an `Event`.

**Comment by quetzyg** [comment]
Fixed via #73
