### ISSUE TITLE
Stop scrolling and zooming out when clicking icons

### ISSUE THREAD

**Issue by SerggioC** [vostpt/api#51]
When we are zoomed in in the map and click an icon we are zoomed out automagically, which is annoying. 

When clicking an icon the popup info window is huge!
Can you make this smaller and add clear information about available fuels? Pricing would be nice too.

In mobile devices, which the majority of accesses come from I believe, the site has some issues. 
When scrolling, the whole page scrolls instead of the map.
The legend gets behind the search field...

**Comment by quetzyg** [comment]
Hi @SerggioC,

Thanks for taking the time to open an issue, although this isn't the correct repository for the problem you're having.

Please report this in [vostpt/greve-transportes-perigosos](https://github.com/vostpt/greve-transportes-perigosos/issues), instead.

cc @Cotemero
