### ISSUE TITLE
[REFACTOR] Docker files

### ISSUE THREAD

**Issue by josepostiga** [vostpt/api#56]
A few things I've noticed with the current Docker files:
- Configuration folders/files are mixed with the codebase, unnecessarily.
- The docker-compose file has some configurations that could be improved (unnecessary mapping of port 9000 in the host machine, for example).
- PHP Dockerfile is missing some useful extensions and configurations (likeXDebug, for example).

**Comment by quetzyg** [comment]
XDebug is already included. About the other things, sure, tidy up the configs.

**Comment by josepostiga** [comment]
Yes, I know the xDebug is installed. I was referencing its configuration.

**Comment by quetzyg** [comment]
Fixed via #57
