### ISSUE TITLE
[FEAT] - List of contributors

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/api#58]
**Request**
List of contributors of the project, not only from the API but also contributors of the App. Ideally to load the list of contributors from the Github Projects: 
- API - https://github.com/vostpt/api 
- MobileApp - https://github.com/vostpt/mobile-app

_Extra points_ 
To have the possibility to add other people, that contributed to the project but are not in the contributors' list of Github.

**Use Case**
- To show the list of contributors for the App in the [Contributors Page](https://github.com/vostpt/mobile-app/issues/17)
- Have the possibility to show the contributors list on the future website.

**Comment by quetzyg** [comment]
Like you've pointed out, there will be contributors that can't be fetched from the GH API. Should we roll our own source of truth, then?

**Comment by OldMetalmind** [comment]
Sure I agree, however, would be nice that it is capable of updating from the GH API for the contributors that are there.

**Comment by quetzyg** [comment]
@OldMetalmind, given you're taking care of this on another repo, this can be closed, right?
