### ISSUE TITLE
[Issue] Pagination URL links

### ISSUE THREAD

**Issue by OldMetalmind** [vostpt/api#61]
### Problem

In all responses with pagination inside field `links` (`first`, `last`, `prev, `next`) all URLs are badly constructed.

#### Example
`GET {{host}}/occurrences` will return `links`: 
```
    ...
    "links": {
        "first": "https://api.vost.pt/v1/occurrences?page=1",
        "last": "https://api.vost.pt/v1/occurrences?page=780",
        "next": "https://api.vost.pt/v1/occurrences?page=2"
    }
    ...
```

While the URLs should be like so: 

```
    ...
    "links": {
        "first": "https://api.vost.pt/v1/occurrences?page[number]=1",
        "last": "https://api.vost.pt/v1/occurrences?page[number]=780",
        "next": "https://api.vost.pt/v1/occurrences?page[number]=2"
    }
    ...
```

#### Problem Detected at 

- `/acronyms`
- `/events`
- `/occurrences`
- `/occurrences/families`
- `/occurrences/species`
- `/occurrences/types`
- `/districts`
- `/counties`
- `/parishes`

**Comment by quetzyg** [comment]
Fixed via #62
